const fs = require('fs');
const path = require('path');

module.exports = async (ctx, db, OWNER_ID) => {
    // 1. Authorization Check (Owner & Sudo)
    const sudoList = await db.collection('sudo_users').distinct('uid');
    const isOwner = (ctx.from.id === OWNER_ID);
    const isSudo = sudoList.includes(ctx.from.id.toString());

    if (!isOwner && !isSudo) {
        return ctx.reply("❌ ᴀᴄᴄᴇꜱꜱ ᴅᴇɴɪᴇᴅ: ʏᴏᴜ ɴᴇᴇᴅ ꜱᴜᴅᴏ/ᴏᴡɴᴇʀ ᴘᴇʀᴍɪꜱꜱɪᴏɴꜱ.");
    }

    // 2. Target Identification
    const target = ctx.message.reply_to_message ? ctx.message.reply_to_message.from : null;
    if (!target) {
        return ctx.reply("⚠️ ᴘʟᴇᴀsᴇ ʀᴇᴘʟʏ ᴛᴏ ᴀ ᴜsᴇʀ's ᴍᴇssᴀɢᴇ ᴛᴏ ᴛʀᴀᴄᴇ ᴛʜᴇᴍ.");
    }

    const uid = target.id.toString();
    const name = target.first_name;

    // 3. Data Extraction (Merging multiple collections)
    const history = await db.collection('user_history').findOne({ uid });
    const globalData = await db.collection('global_users').findOne({ uid });

    // 4. Report Building
    let log = `====================================\n`;
    log += `   🕵️‍♂️ YURI AI INVESTIGATION REPORT   \n`;
    log += `====================================\n\n`;
    
    log += `[BASIC INFO]\n`;
    log += `• User ID: ${uid}\n`;
    log += `• Name: ${name} ${target.last_name || ""}\n`;
    log += `• Username: @${target.username || "N/A"}\n`;
    log += `• Status: ${target.is_bot ? "🤖 BOT" : "👤 HUMAN"}\n\n`;

    if (history) {
        log += `[IDENTITY LOGS (Sangmata Core)]\n`;
        log += `• Known Names: ${history.names.join(' | ')}\n`;
        log += `• Known Usernames: ${history.usernames.join(' | ')}\n\n`;
    }

    if (globalData) {
        log += `[GLOBAL FOOTPRINTS]\n`;
        log += `• Total Messages: ${globalData.total_messages || 0}\n`;
        log += `• Last Activity: ${globalData.last_seen}\n`;
        log += `• Visible Groups:\n`;
        
        if (globalData.seen_in_groups && globalData.seen_in_groups.length > 0) {
            globalData.seen_in_groups.forEach(g => {
                log += `  - [${g.gid}] ${g.gName}\n`;
            });
        } else {
            log += `  - No specific group records found.\n`;
        }
    } else {
        log += `[ALERT]: No global database entry found. Target is possibly a ghost or new.\n`;
    }

    log += `\n====================================\n`;
    log += `REPORT GENERATED BY YURI AI | SYSTEM: ENCRYPTED\n`;
    log += `====================================`;

    // 5. File Handling (Vercel Friendly)
    const fileName = `TRACE_${uid}_${Date.now()}.txt`;
    const filePath = path.join('/tmp', fileName);

    try {
        fs.writeFileSync(filePath, log);

        // Sending Document
        await ctx.replyWithDocument(
            { source: filePath, filename: fileName },
            { 
                caption: `🔍 <b>ᴅᴇᴇᴘ ᴛʀᴀᴄᴇ ᴄᴏᴍᴘʟᴇᴛᴇᴅ</b>\n👤 ᴛᴀʀɢᴇᴛ: <code>${name}</code>\n🆔 ɪᴅ: <code>${uid}</code>`,
                parse_mode: 'HTML' 
            }
        );
    } catch (err) {
        console.error("Tracing Error:", err);
        ctx.reply("❌ Error generating trace file.");
    } finally {
        // Clean up file from /tmp
        if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
    }
};
